-- Day 3：Scania APS MySQL 建表脚本
-- 本文件由 scripts/generate_mysql_schema.py 根据原始 CSV 表头生成。
-- 只定义表结构，不导入数据，不做缺失值填充、字段删除或建模。
-- 原始数据共有 170 个匿名数值特征，标签字段为 class。

USE scania_aps_project;

-- 为避免误删已导入的数据，本脚本只使用 CREATE TABLE IF NOT EXISTS。
-- 如果确实需要重建表，请先手动备份并在本地确认后再执行删表操作。

CREATE TABLE IF NOT EXISTS `raw_aps_train` (
  `sample_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '导入后的行号主键',
  `class` VARCHAR(10) NULL COMMENT '原始标签：pos 表示 APS 相关故障，neg 表示非 APS 相关故障',
  `aa_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ab_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ac_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ad_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ae_000` DOUBLE NULL COMMENT '匿名数值特征',
  `af_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_001` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_002` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_003` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_004` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_005` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_006` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_007` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_008` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_009` DOUBLE NULL COMMENT '匿名数值特征',
  `ah_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ai_000` DOUBLE NULL COMMENT '匿名数值特征',
  `aj_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ak_000` DOUBLE NULL COMMENT '匿名数值特征',
  `al_000` DOUBLE NULL COMMENT '匿名数值特征',
  `am_0` DOUBLE NULL COMMENT '匿名数值特征',
  `an_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ao_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ap_000` DOUBLE NULL COMMENT '匿名数值特征',
  `aq_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ar_000` DOUBLE NULL COMMENT '匿名数值特征',
  `as_000` DOUBLE NULL COMMENT '匿名数值特征',
  `at_000` DOUBLE NULL COMMENT '匿名数值特征',
  `au_000` DOUBLE NULL COMMENT '匿名数值特征',
  `av_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ax_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_001` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_002` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_003` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_004` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_005` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_006` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_007` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_008` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_009` DOUBLE NULL COMMENT '匿名数值特征',
  `az_000` DOUBLE NULL COMMENT '匿名数值特征',
  `az_001` DOUBLE NULL COMMENT '匿名数值特征',
  `az_002` DOUBLE NULL COMMENT '匿名数值特征',
  `az_003` DOUBLE NULL COMMENT '匿名数值特征',
  `az_004` DOUBLE NULL COMMENT '匿名数值特征',
  `az_005` DOUBLE NULL COMMENT '匿名数值特征',
  `az_006` DOUBLE NULL COMMENT '匿名数值特征',
  `az_007` DOUBLE NULL COMMENT '匿名数值特征',
  `az_008` DOUBLE NULL COMMENT '匿名数值特征',
  `az_009` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_001` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_002` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_003` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_004` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_005` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_006` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_007` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_008` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_009` DOUBLE NULL COMMENT '匿名数值特征',
  `bb_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bc_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bd_000` DOUBLE NULL COMMENT '匿名数值特征',
  `be_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bf_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bg_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bh_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bi_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bj_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bk_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bl_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bm_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bn_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bo_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bp_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bq_000` DOUBLE NULL COMMENT '匿名数值特征',
  `br_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bs_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bt_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bu_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bv_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bx_000` DOUBLE NULL COMMENT '匿名数值特征',
  `by_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bz_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ca_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cb_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cc_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cd_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ce_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cf_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cg_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ch_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ci_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cj_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ck_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cl_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cm_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_001` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_002` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_003` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_004` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_005` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_006` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_007` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_008` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_009` DOUBLE NULL COMMENT '匿名数值特征',
  `co_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cp_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cq_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cr_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_001` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_002` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_003` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_004` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_005` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_006` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_007` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_008` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_009` DOUBLE NULL COMMENT '匿名数值特征',
  `ct_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cu_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cv_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cx_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cy_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cz_000` DOUBLE NULL COMMENT '匿名数值特征',
  `da_000` DOUBLE NULL COMMENT '匿名数值特征',
  `db_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dc_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dd_000` DOUBLE NULL COMMENT '匿名数值特征',
  `de_000` DOUBLE NULL COMMENT '匿名数值特征',
  `df_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dg_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dh_000` DOUBLE NULL COMMENT '匿名数值特征',
  `di_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dj_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dk_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dl_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dm_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dn_000` DOUBLE NULL COMMENT '匿名数值特征',
  `do_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dp_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dq_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dr_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ds_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dt_000` DOUBLE NULL COMMENT '匿名数值特征',
  `du_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dv_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dx_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dy_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dz_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ea_000` DOUBLE NULL COMMENT '匿名数值特征',
  `eb_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ec_00` DOUBLE NULL COMMENT '匿名数值特征',
  `ed_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_001` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_002` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_003` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_004` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_005` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_006` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_007` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_008` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_009` DOUBLE NULL COMMENT '匿名数值特征',
  `ef_000` DOUBLE NULL COMMENT '匿名数值特征',
  `eg_000` DOUBLE NULL COMMENT '匿名数值特征',
  PRIMARY KEY (`sample_id`),
  KEY `idx_class` (`class`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Scania APS 原始宽表：raw_aps_train';


CREATE TABLE IF NOT EXISTS `raw_aps_test` (
  `sample_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '导入后的行号主键',
  `class` VARCHAR(10) NULL COMMENT '原始标签：pos 表示 APS 相关故障，neg 表示非 APS 相关故障',
  `aa_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ab_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ac_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ad_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ae_000` DOUBLE NULL COMMENT '匿名数值特征',
  `af_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_001` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_002` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_003` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_004` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_005` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_006` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_007` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_008` DOUBLE NULL COMMENT '匿名数值特征',
  `ag_009` DOUBLE NULL COMMENT '匿名数值特征',
  `ah_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ai_000` DOUBLE NULL COMMENT '匿名数值特征',
  `aj_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ak_000` DOUBLE NULL COMMENT '匿名数值特征',
  `al_000` DOUBLE NULL COMMENT '匿名数值特征',
  `am_0` DOUBLE NULL COMMENT '匿名数值特征',
  `an_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ao_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ap_000` DOUBLE NULL COMMENT '匿名数值特征',
  `aq_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ar_000` DOUBLE NULL COMMENT '匿名数值特征',
  `as_000` DOUBLE NULL COMMENT '匿名数值特征',
  `at_000` DOUBLE NULL COMMENT '匿名数值特征',
  `au_000` DOUBLE NULL COMMENT '匿名数值特征',
  `av_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ax_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_001` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_002` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_003` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_004` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_005` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_006` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_007` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_008` DOUBLE NULL COMMENT '匿名数值特征',
  `ay_009` DOUBLE NULL COMMENT '匿名数值特征',
  `az_000` DOUBLE NULL COMMENT '匿名数值特征',
  `az_001` DOUBLE NULL COMMENT '匿名数值特征',
  `az_002` DOUBLE NULL COMMENT '匿名数值特征',
  `az_003` DOUBLE NULL COMMENT '匿名数值特征',
  `az_004` DOUBLE NULL COMMENT '匿名数值特征',
  `az_005` DOUBLE NULL COMMENT '匿名数值特征',
  `az_006` DOUBLE NULL COMMENT '匿名数值特征',
  `az_007` DOUBLE NULL COMMENT '匿名数值特征',
  `az_008` DOUBLE NULL COMMENT '匿名数值特征',
  `az_009` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_001` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_002` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_003` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_004` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_005` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_006` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_007` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_008` DOUBLE NULL COMMENT '匿名数值特征',
  `ba_009` DOUBLE NULL COMMENT '匿名数值特征',
  `bb_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bc_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bd_000` DOUBLE NULL COMMENT '匿名数值特征',
  `be_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bf_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bg_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bh_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bi_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bj_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bk_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bl_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bm_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bn_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bo_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bp_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bq_000` DOUBLE NULL COMMENT '匿名数值特征',
  `br_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bs_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bt_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bu_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bv_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bx_000` DOUBLE NULL COMMENT '匿名数值特征',
  `by_000` DOUBLE NULL COMMENT '匿名数值特征',
  `bz_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ca_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cb_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cc_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cd_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ce_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cf_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cg_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ch_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ci_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cj_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ck_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cl_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cm_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_001` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_002` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_003` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_004` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_005` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_006` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_007` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_008` DOUBLE NULL COMMENT '匿名数值特征',
  `cn_009` DOUBLE NULL COMMENT '匿名数值特征',
  `co_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cp_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cq_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cr_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_001` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_002` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_003` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_004` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_005` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_006` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_007` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_008` DOUBLE NULL COMMENT '匿名数值特征',
  `cs_009` DOUBLE NULL COMMENT '匿名数值特征',
  `ct_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cu_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cv_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cx_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cy_000` DOUBLE NULL COMMENT '匿名数值特征',
  `cz_000` DOUBLE NULL COMMENT '匿名数值特征',
  `da_000` DOUBLE NULL COMMENT '匿名数值特征',
  `db_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dc_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dd_000` DOUBLE NULL COMMENT '匿名数值特征',
  `de_000` DOUBLE NULL COMMENT '匿名数值特征',
  `df_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dg_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dh_000` DOUBLE NULL COMMENT '匿名数值特征',
  `di_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dj_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dk_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dl_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dm_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dn_000` DOUBLE NULL COMMENT '匿名数值特征',
  `do_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dp_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dq_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dr_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ds_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dt_000` DOUBLE NULL COMMENT '匿名数值特征',
  `du_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dv_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dx_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dy_000` DOUBLE NULL COMMENT '匿名数值特征',
  `dz_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ea_000` DOUBLE NULL COMMENT '匿名数值特征',
  `eb_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ec_00` DOUBLE NULL COMMENT '匿名数值特征',
  `ed_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_000` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_001` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_002` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_003` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_004` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_005` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_006` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_007` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_008` DOUBLE NULL COMMENT '匿名数值特征',
  `ee_009` DOUBLE NULL COMMENT '匿名数值特征',
  `ef_000` DOUBLE NULL COMMENT '匿名数值特征',
  `eg_000` DOUBLE NULL COMMENT '匿名数值特征',
  PRIMARY KEY (`sample_id`),
  KEY `idx_class` (`class`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Scania APS 原始宽表：raw_aps_test';


CREATE TABLE IF NOT EXISTS `dataset_overview` (
  `dataset` VARCHAR(20) NOT NULL COMMENT 'train 或 test',
  `total_rows` BIGINT NOT NULL,
  `total_columns` INT NOT NULL,
  `feature_count` INT NOT NULL,
  `label_column_exists` TINYINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`dataset`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据集规模概览，可由 SQL 查询结果写入';

CREATE TABLE IF NOT EXISTS `label_distribution` (
  `dataset` VARCHAR(20) NOT NULL COMMENT 'train 或 test',
  `class` VARCHAR(10) NOT NULL COMMENT 'pos 或 neg',
  `sample_count` BIGINT NOT NULL,
  `sample_ratio` DOUBLE NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`dataset`, `class`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='标签分布统计，可由 SQL 查询结果写入';

CREATE TABLE IF NOT EXISTS `feature_missing_summary` (
  `dataset` VARCHAR(20) NOT NULL COMMENT 'train 或 test',
  `summary_scope` VARCHAR(20) NOT NULL DEFAULT 'overall' COMMENT 'overall 或 by_class',
  `class_label` VARCHAR(10) NOT NULL DEFAULT 'all' COMMENT 'overall 使用 all，分类统计使用 pos/neg',
  `feature_name` VARCHAR(64) NOT NULL,
  `missing_count` BIGINT NOT NULL,
  `total_count` BIGINT NOT NULL,
  `missing_rate` DOUBLE NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`dataset`, `summary_scope`, `class_label`, `feature_name`),
  KEY `idx_feature_missing_rate` (`feature_name`, `missing_rate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='字段缺失率统计，可导入 Day 2 产物或由生成 SQL 得到';

CREATE TABLE IF NOT EXISTS `model_prediction_result` (
  `prediction_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dataset` VARCHAR(20) NOT NULL COMMENT '后续通常为 test 或 validation',
  `sample_id` BIGINT UNSIGNED NOT NULL,
  `true_class` VARCHAR(10) NULL,
  `true_target` TINYINT NULL,
  `predicted_probability` DOUBLE NULL,
  `predicted_target` TINYINT NULL,
  `threshold` DOUBLE NULL,
  `risk_level` VARCHAR(20) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`prediction_id`),
  KEY `idx_prediction_dataset_sample` (`dataset`, `sample_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='后续模型预测结果回写预留表，Day 3 不写入真实数据';
